# Scripts path
$scrPath = $HOME/.local/bin

# Monitor settings
monitor = DP-1, 2560x1440@165, 0x0, 1
monitor = DP-2, 1680x1050@60, 440x-1050, 1

# Workspaces
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2

# Per-workspace layouts
workspace = 1, layout:scrolling
workspace = 2, layout:scrolling
workspace = 3, layout:scrolling
workspace = 4, layout:master
workspace = 5, layout:master

# Startup processes
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment --all
exec-once = systemctl --user start hyprpolkitagent
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpaper
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = waybar
exec-once = mako
exec-once = hyprsunset
exec-once = hypridle
exec-once = openrgb --profile Default
exec-once = sh -lc 'sleep 2 && coolercontrol >/dev/null 2>&1 & disown'
exec-once = corectrl --minimize-systray
exec-once = hyprctl dispatch workspace 5

# Environment variables
env = PATH,$PATH:$scrPath
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland
env = GDK_SCALE,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_STYLE_OVERRIDE,kvantum
env = QT_QPA_PLATFORMTHEME,kvantum
env = MOZ_ENABLE_WAYLAND,1
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24
env = HYPRSHOT_DIR,/home/abov/Pictures/Screenshots
env = GTK_THEME,Tokyonight-Dark

# Decoration
decoration {
  rounding = 12
  rounding_power = 2.5

  shadow {
    enabled = true
    range = 20
    render_power = 3
    ignore_window = true
    color = 0xee1a1a1a
  }

  blur {
    enabled = true
    size = 3
    passes = 1
    new_optimizations = true
  }
}

# Cursor settings
cursor {
    no_warps = false
    warp_on_change_workspace = 0
}

# Input
input {
    kb_layout = us,sk
    follow_mouse = 1
    #kb_options = caps:swapescape # great for coding, sucks for gaming due to lack of support
}

# Mouse settings
device {
    name = wl-wlmouse-mini-receiver-1 # WLMouse (Wireless)
    sensitivity = -0.5
    accel_profile = flat
}

device {
    name = wl-wlmouse-mini # WLMouse (Wired)
    sensitivity = -0.5
    accel_profile = flat
}

# Window layouts
dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_status = slave
    mfact = 0.7
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 1.0
    focus_fit_method = 1
    follow_focus = true
}

# General settings
general {
    allow_tearing = true # Trades visual quality for latency improvement, ideal for competitive games
    gaps_out = 4
    border_size = 3
    col.active_border = rgb(7aa2f7) rgb(bb9af7) 45deg

}

# Render settings
render {
    direct_scanout = 2
    new_render_scheduling = true
    send_content_type = true
}

# Misc
misc {
    vrr = 2
    vfr = true
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    focus_on_activate = false
}

# XWayland configuration
xwayland {
    force_zero_scaling = true
}

# Hyprland plugins
plugin {
    csgo-vulkan-fix {
        fix_mouse = true
        vkfix-app = cs2, 1280, 960
    }
}

# Sources
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
